import { useEffect } from "react";
import { Link } from "react-router-dom";
import logoUrl from "../enterprate-logo.png";

export default function DisclaimerPage() {
  useEffect(() => {
    document.body.style.overflow = "auto";
    return () => { document.body.style.overflow = ""; };
  }, []);

  return (
    <div className="min-h-screen bg-white text-slate-800">
      <header className="sticky top-0 z-50 border-b border-slate-100 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-4xl items-center justify-between">
          <Link to="/"><img src={logoUrl} alt="EnterprateAI" className="h-7 w-auto" /></Link>
          <div className="flex gap-4 text-sm text-slate-500">
            <Link to="/legal/privacy" className="hover:text-slate-700">Privacy Policy</Link>
            <Link to="/legal/terms" className="hover:text-slate-700">Terms of Service</Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-14">
        <h1 className="mb-10 text-3xl font-bold text-slate-900">Operating Environment Disclaimer</h1>

        <div className="rounded-xl border border-amber-200 bg-amber-50 px-6 py-5 text-sm text-amber-800 dark:border-amber-700 dark:bg-amber-900/20 dark:text-amber-300">
          <p className="font-semibold">AI Use Notice</p>
          <p className="mt-1">EnterprateAI may generate inaccurate or incomplete outputs. Please review important information before making business decisions.</p>
        </div>

        <div className="mt-10 space-y-6 text-sm leading-relaxed text-slate-600">
          <p>EnterprateAI is a decision intelligence platform designed to support business planning, analysis, and operational tasks. It uses structured data inputs, calculations, and AI-assisted features to generate outputs such as business plans, proposals, simulations, risk insights, documents, and recommendations.</p>

          <p>While we aim to make EnterprateAI as accurate and useful as possible, outputs generated by the platform may be incomplete, inaccurate, out of date, or not suitable for your specific circumstances.</p>

          <p><strong className="text-slate-800">Outputs are decision-support tools only.</strong> They are not a substitute for professional judgement, and you should not rely solely on platform outputs when making legal, financial, tax, regulatory, employment, investment, or other consequential business decisions.</p>

          <p>You should review all outputs carefully before using, sharing, publishing, or acting on them. Where appropriate, you should seek advice from a qualified professional, such as an accountant, lawyer, financial adviser, or relevant specialist.</p>

          <p>Scenario simulations, risk scores, viability assessments, Fragility Index outputs, survival scores, and growth recommendations are based on the data you provide and the assumptions built into the platform. They reflect modelled projections, not guarantees of future performance or outcomes. Actual results may differ significantly due to factors outside the platform's assumptions, including market conditions, competition, execution quality, customer behaviour, regulatory changes, and cost variations.</p>

          <p>EnterprateAI does not provide legal, tax, accounting, financial, investment, immigration, or regulatory advice. No output from the platform should be treated as such.</p>

          <p>Enterprate Limited accepts no liability for decisions made based on platform outputs. Our full liability terms are set out in our <Link to="/legal/terms" className="text-indigo-600 hover:underline">Terms of Service</Link>.</p>

          <p>If you have questions about how the platform works or the limitations of its outputs, contact us at <a href="mailto:admin@enterprate.ai" className="text-indigo-600 hover:underline">admin@enterprate.ai</a>.</p>
        </div>

        <div className="mt-10 text-sm text-slate-500">
          <p>Enterprate Limited · London, United Kingdom</p>
          <p>Website: <a href="https://www.enterprate.ai" className="text-indigo-600 hover:underline">www.enterprate.ai</a></p>
        </div>
      </main>

      <footer className="border-t border-slate-100 px-6 py-6 text-center text-xs text-slate-400">
        © {new Date().getFullYear()} Enterprate Limited. All rights reserved.&nbsp;·&nbsp;
        <Link to="/legal/privacy" className="hover:underline">Privacy Policy</Link>&nbsp;·&nbsp;
        <Link to="/legal/terms" className="hover:underline">Terms of Service</Link>
      </footer>
    </div>
  );
}
